export { RHFInput, RHFInput as Input } from './components/RHFInput'
export { RHFPassword, RHFPassword as PasswordInput } from './components/RHFPassword'
export { RHFSwitch, RHFSwitch as Switch } from './components/RHFSwitch'
export { FormContainer, FormContainer as ShadcnFormContainer } from './FormContainer'
export { RHFShadcnProvider } from './registry'
